
services:
  app:
    build: .
    container_name: jwt_spring_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/jwt
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: PHW#84#jeor
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL8Dialect

  db:
    image: mysql:8
    container_name: mysql_db
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: jwt
      MYSQL_ROOT_PASSWORD: PHW#84#jeor
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

volumes:
  mysql_data: